import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/contexts/sidebar-context";
import "./globals.css";
import DashboardSidebar from "@/components/sidebar";
import Header from "@/components/header";
import ContentWrapper from "@/app/wrapper"; // New client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex">
            <DashboardSidebar />
            <div className="flex-1 flex flex-col">
              <Header />
              <ContentWrapper>
                {children}
              </ContentWrapper>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}